### ISSUE TITLE
Javascript Solution

### ISSUE THREAD

**Issue by umranium** [adricl/apply.dataprocessors.com.au#1]
Hi Adric,

This isn't really an issue, but I couldn't find any other way to contact you.

I came across your solution while Googling. I also tried using a (somewhat) similar way with Java. I came across the same error. I thought it was something to do with cookies. I then thought of using javascript directly on the page. Check out the javascript solution that worked for me here: https://github.com/umranium/apply.dataprocessors.com.au. It's somewhat manual, but it works.

Regards,
Umran.

**Comment by adricl** [comment]
Hi Umaran,

Thanks for this. Did you get any contract from this company? I never got my code to work. It submitted the correct result but I just got an error page once I submitted it. Same as yours issue with java I am guessing. I am not sure what was wrong. 

I like your approach though. It was so simple. haha Oh well. 

Cheers,
adric

**Comment by adricl** [comment]
https://github.com/search?q=apply.dataprocessors.com.au&type=Code&utf8=%E2%9C%93

Seems like a few people had a go.

**Comment by umranium** [comment]
They did contact me, but only after I emailed them suggestions on how to improve the puzzle. However, after a telephone interview they said that my skills don't fit what they need.

That's interesting. I didn't think to search on github. I wonder how many of those solutions worked.
